### ISSUE TITLE
Excercise 1: relation between time-duration and semi-latus rectum is not linear

### ISSUE THREAD

**Issue by avivajpeyi** [OllieBurke/EMRI_Workshop#2]
![Screenshot from 2024-02-13 14-52-38](https://github.com/OllieBurke/EMRI_Workshop/assets/15642823/a70acc83-3138-41ae-8905-f349ab5839b0)
![Screenshot from 2024-02-13 14-52-25](https://github.com/OllieBurke/EMRI_Workshop/assets/15642823/779ee5ef-0292-4b44-bc9c-9746428d9ff1)

**Comment by OllieBurke** [comment]
Fixed! Thank you!  It should read as "Exponential", only linear on a log-log plot.
